### ISSUE TITLE
default json file shows customer value different than what is in documentation

### ISSUE THREAD

**Issue by mfsbo** [EazyCollectServices/EazyCollectSDK-Dotnet#1]
https://github.com/EazyCollectServices/EazyCollectSDK-Dotnet/tree/master/EazySDK#acceptable-arguments-6 line suggests that the default is set to true
https://github.com/EazyCollectServices/EazyCollectSDK-Dotnet/blob/master/EazySDK/appsettings.json#L29 file sets it to false.

What would be the value written if the file does not exist?

**Comment by Glazbee** [comment]
This has now been corrected in the file, and the value should be True
