### ISSUE TITLE
Default Config Values

### ISSUE THREAD

**Issue by ScarlettCode** [EazyCollectServices/EazyCollectSDK-Dotnet#4]
When using the API, I'm getting an error which I've tracked down to the following bit of code

PaymentPostChecks.cs - Line 40

`OngoingProcessingDays = int.Parse(Settings.GetSection("directDebitProcessingDays")["OngoingProcessingDays"]);`

I'm not setting these values anywhere in my app. Should I be settings all these values in my app or am I missing something?

These are the ones I might need to set?
```

"directDebitProcessingDays": {
    "InitialProcessingDays": 10,
    "OngoingProcessingDays": 5
  },
  "contracts": {
    "AutoFixStartDate": false,
    "AutoFixTerminationTypeAdHoc": false,
    "AutoFixAtTheEndAdHoc": false,
    "AutoFixPaymentDayInMonth": false,
    "AutoFixPaymentMonthInYear": false
  },
  "payments": {
    "AutoFixPaymentDate": false,
    "IsCreditAllowed": false
  },
  "warnings": {
    "CustomerSearchWarning": true
  },
  "other": {
    "BankHolidayUpdateDays": 30,
    "ForceUpdateSchedulesOnRun": false
  }
```

**Comment by eazyJoe** [comment]
@ScarlettCode The default values should be written to an internal appSettings.json file when you first call
```
var handler = new ClientHandler();
var settings = handler.Settings();
```
I can see that your client should be using the default `OngoingProcessingDays` value of 5 so you shouldn't need to update this manually.

**Comment by ScarlettCode** [comment]
@eazyJoe I'm guessing that because I already have an appsettings.json file for my own setting that the below line finds my version and then doesn't ever create the file with the default config.

```
if (!File.Exists(Directory.GetCurrentDirectory() + "/appSettings.json"))
{
    SettingsWriter writer = new SettingsWriter();
}
```
Considering appsettings.json is a default aspnet settings file name shouldn't the EazyCollectSDK settings be of a different name, maybe appsettings-eazycollect.json

Also looking at the code from what I can tell the settings are never actually written even if an appsettings.json file doesn't exist

https://github.com/EazyCollectServices/EazyCollectSDK-Dotnet/blob/854279338ee73788fb2b4b6fd4eeae48710a2bb4/EazySDK/SettingsManager.cs#L11

Unless I'm missing something GetDefaultSettings is only called by CreateSettingsInMemory which is never called by anything. 

Thanks
