### ISSUE TITLE
Parameters null check

### ISSUE THREAD

**Issue by ScarlettCode** [EazyCollectServices/EazyCollectSDK-Dotnet#5]
During contract creation, CheckScheduleNameIsAvailable is called and that ends up doing a GET request. This crashes because Parameters is null. I think a null check if required at the bottom line

https://github.com/EazyCollectServices/EazyCollectSDK-Dotnet/blob/854279338ee73788fb2b4b6fd4eeae48710a2bb4/EazySDK/Session.cs#L141

**Comment by eazyJoe** [comment]
@ScarlettCode The method should continue if Parameters in null:
```
// If no parameters exist, continue
catch (NullReferenceException)
{
}
```
This will make a call to the /schedules endpoint without passing any query params. I've not been able to reproduce this on contract creation - are you able to please share your call to `post.Contract()`?

**Comment by ScarlettCode** [comment]
Ah my bad, because I'm running it debug mode it hits the exception but it does continue
